site_name: SwiftWing S3 Plane Tutorial

theme:
  name: readthedocs

nav:
  - 主页: index.md
  - 产品介绍:
    - 产品简介: 产品介绍/产品简介.md
    - 功能介绍: 产品介绍/功能介绍.md
    - 免责声明: 产品介绍/免责声明.md
    - 物品清单: 产品介绍/物品清单.md
    - 硬件规格: 产品介绍/硬件规格.md
  - 快速上手:
    - 开箱组装: 快速上手/开箱组装.md
    - 设备结构检查: 快速上手/设备结构检查.md
    - 电池充电: 快速上手/电池充电.md
    - 遥控器充电: 快速上手/遥控器充电.md
    - 准备遥控器: 快速上手/准备遥控器.md
    - 准备通信链路: 快速上手/准备通信链路.md
    - APM飞控教程: 快速上手/APM飞控教程.md
    - PX4飞控教程: 快速上手/PX4飞控教程.md
    - 飞行场地准备: 快速上手/飞行场地准备.md
    - 垂起固定翼起飞前地面测试: 快速上手/垂起固定翼起飞前地面测试.md
    - 双发固定翼起飞前地面测试: 快速上手/双发固定翼起飞前地面测试.md
  - 进阶飞行:
    - 垂起固定翼手动飞行介绍: 进阶飞行/垂起固定翼手动飞行介绍.md
    - 垂起固定翼完整飞行演示: 进阶飞行/垂起固定翼完整飞行演示.md
    - 双发固定翼手动飞行介绍: 进阶飞行/双发固定翼手动飞行介绍.md
    - 双发固定翼完整飞行演示: 进阶飞行/双发固定翼完整飞行演示.md
    - 资源下载: 进阶飞行/资源下载.md
  - 产品维护:
    - 维护保养: 产品维护/维护保养.md
  - D6 Pro 说明书: D6_Pro_说明书/index.md